### ISSUE TITLE
antidote update does not update to 1.8.2 (remains at 1.8.1)

### ISSUE THREAD

**Issue by pro-sumer** [mattmc3/antidote#117] opened 2023-03-26 11:59 UTC
```
> antidote update
...
Updating antidote...
Antidote self-update complete.

antidote version 1.8.1
```

Shouldn't this update to 1.8.2 (released yesterday)?

**Comment by mattmc3** [comment] 2023-03-26 12:13
Yes, good catch. Cutting a new release with a proper bumpversion. Dupe of #116.

**Closed by mattmc3** 2023-03-26 12:13 UTC
